@BASE = http://127.0.0.1:8000

###

# @name create
POST {{BASE}}/games
Content-Type: application/json

{"fen": "8/4P3/8/8/8/6P1/1k4P1/6K1 w - - 1 57"}

###
@gameid = {{create.response.body.key}}

###

GET {{BASE}}/games/{{gameid}}/move_suggestion?move_ms=10000

###

POST {{BASE}}/games/{{gameid}}/move
Content-Type: application/json

{"move": "e2f1"}