@BASE = http://127.0.0.1:8000

###

# @name create
POST {{BASE}}/games
Content-Type: application/json

{"fen": "r3kb1r/1q1n1ppp/pp1ppn2/8/2PNP3/1PN2PP1/P5KP/R1BQR3 b kq - 0 13"}

###
@gameid = {{create.response.body.key}}

###

GET {{BASE}}/games/{{gameid}}/move_suggestion

###

POST {{BASE}}/games/{{gameid}}/move
Content-Type: application/json

{"move": "e2f1"}